version: '3.8'

services:
  capuletshuffleboard:
    image: capuletshuffleboard
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - OPENCV_VERSION=4.5.1
    volumes:
      - /opt/vc:/opt/vc
